[package]
name = "emulation-qemu-riscv-main"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2021"

[dependencies]
embedded-hal = { workspace = true }
embedded-hal-nb = { workspace = true }
nb = "1"
ns16550a = "0.1.0"
rustsbi = { version = "=0.4.0", features = ["machine"] }

layoutflash = { path = "../../../../lib/layoutflash" }
log = { path = "../../../../lib/log" }
oreboot-arch = { path = "../../../../arch", features = ["riscv64"] }
oreboot_compression = { path = "../../../../lib/compression" }
zlib-rs = { version = "0.4.2", default-features = false }
