OREBOOT=$(abspath $(CURDIR)/../../../../)
TARGET     = x86_64-unknown-none-oreboot
include ../../../../Makefile.inc
include ../../../../Makefile.mainboard.inc
cibuild: $(IMAGE)
ciclippy: skipclippy
citest: skiptest
